gitlab:
  image: gitlab/gitlab-ce:latest
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.novate.net'
  ports:
    - 22:22
    - 8001:80
  volumes:
    - /docker/gitlab/config:/etc/gitlab
    - /docker/gitlab/logs:/var/log/gitlab
    - /docker/gitlab/data:/var/opt/gitlab
